//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace BlogDetailsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlogDetail
    {
        public tblBlogDetail()
        {

        }
        public int BlogId { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Title { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Description { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Author { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
