//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace BlogDetailsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoginDetail
    {
        public int UserId { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Username { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [RegularExpression("^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$", ErrorMessage = "Invalid Email Id")]
        public string Email_Id { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Password { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    }
}
