//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogDetailsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLikeDetail
    {
        public int Id { get; set; }
        public Nullable<int> BlogId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LikedOn { get; set; }
    }
}
